changelog:
  categories:
    - title: "🚀 Neue Features"
      labels:
        - feature
    - title: "💥 Enhancements"
      labels:
        - enhancement
    - title: "🐛 Bug Fixes"
      labels:
        - bug
