---
###################################################
# StorageClass used for local storage only!
###################################################
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: dev-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer