FROM openliberty/open-liberty:20.0.0.3-full-java8-openj9-ubi

#FROM open-liberty:kernel

# Imixs-Office-Workflow
MAINTAINER ralph.soika@imixs.com

# Copy postgres JDBC driver
COPY ./src/docker/configuration/openliberty/postgresql-9.4.1212.jar /opt/ol/wlp/lib

# Add config
COPY --chown=1001:0 ./src/docker/configuration/openliberty/server.xml /config/server.xml

# Activate Debug Mode...
#COPY --chown=1001:0 ./src/docker/configuration/openliberty/jvm.options /config/

# Copy sample application
COPY ./imixs-office-workflow-app/target/imixs-office-workflow*.war /config/dropins/





# Default setting for the verbose option
ARG VERBOSE=false

# Optional functionality
#ARG SSL=true
#ARG MP_MONITORING=true

# This script will add the requested XML snippets and grow image to be fit-for-purpose
RUN configure.sh


