version: '3.1'

services:

  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_USER: "imixs"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_DB: "office"      
    volumes: 
      - dbdata:/var/lib/postgresql/data


  app:
    image: imixs/imixs-office-workflow
    depends_on:
      - db
    environment:
      WILDFLY_PASS: "adminadmin"
      POSTGRES_USER: "imixs"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/office"
    volumes: 
      - appdata:/home/imixs
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"

       
volumes:
  dbdata:
  appdata:

