version: "3"

services:
  ##################################
  # Postgres Server
  ##################################
  dbkeycloak:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - dbkeycloak:/var/lib/postgresql/data

  ##################################
  # Keycloak Server
  ##################################
  keycloak:
    # latest
    image: quay.io/keycloak/keycloak:23.0.5
    #container_name: "keycloak"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ./keycloak.conf:/opt/keycloak/conf/keycloak.conf
    command:
      - start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=adminadmin
      # DATABASE Config
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://dbkeycloak:5432/keycloak
      - KC_DB_USER=keycloak
      - KC_DB_PASSWORD=adminadmin
      #DB_PASSWORD_FILE: Specify user’s password to use to authenticate to the database via file input (alternative to DB_PASSWORD).
    #  - PROXY_ADDRESS_FORWARDING=true
    #  - VIRTUAL_HOST=dev-keycloak.mydomain.com
    #  - VIRTUAL_PORT=8080
    #  - LETSENCRYPT_HOST=dev-keycloak.mydomain.com
    #networks:
    #  - internal
    ports:
      - "8084:8080"

  dboffice:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: office
    volumes:
      - dbdata:/var/lib/postgresql/data
      #- dboffice:/var/lib/postgresql/data

  app:
    image: imixs/imixs-office-workflow
    depends_on:
      - dboffice
    environment:
      TZ: "CET"
      LANG: "en_US.UTF-8"
      JAVA_OPTS: "-Dnashorn.args=--no-deprecation-warning"
      MAILGATEWAY: "localhost"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://dboffice/office"

      OIDCCONFIG_ISSUERURI: "http://keycloak.imixs.local:8084/realms/imixs-office-workflow"
      OIDCCONFIG_CLIENTID: "imixs"
      OIDCCONFIG_CLIENTSECRET: "RBX0YBVvrK84Cpq8CIRXISpy2X7mjpRJ"
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    volumes:
      - ./deployments:/opt/jboss/wildfly/standalone/deployments/
    # Mapping the host ip to the container
    # This setting is used for local testing only
    # Wildfly can access the keycloak server via the external host address
    extra_hosts:
      - "keycloak.imixs.local:host-gateway"

  # imixsadmin:
  #   image: imixs/imixs-admin
  #   ports:
  #     - "8888:8080"

volumes:
  dbkeycloak:
  dbdata:
  #dboffice:
