version: "3.6"
services:
  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: office
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    image: imixs/imixs-office-workflow:latest
    depends_on:
      - db
    environment:
      TZ: "CET"
      LANG: "en_US.UTF-8"
      JAVA_OPTS: "-Dnashorn.args=--no-deprecation-warning"
      DEBUG: "true"
      MAILGATEWAY: "localhost"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/office"

      OCR_SERVICE_ENDPOINT: "http://tika:9998/tika"
      # MODEL | AUTO
      OCR_SERVICE_MODE: "MODEL"
      #OCR_STRATEGY: "NO_OCR, OCR_ONLY, OCR_AND_TEXT_EXTRACTION, AUTO (default)"
      OCR_STRATEGY: "NO_OCR"
      OCR_FILEPATTERN: "(PDF|pdf)$"
      OCR_MAXPDFPAGES: 10

      ASYNCEVENT_PROCESSOR_ENABLED: "true"
      ASYNCEVENT_PROCESSOR_INITIALDELAY: "5000"

      # LLM Integration
      LLM_CONFIG_FILE: /opt/jboss/imixs-llm.xml

    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    volumes:
      - ./deployments:/opt/jboss/wildfly/standalone/deployments/
      - ./keys/imixs-llm.xml:/opt/jboss/imixs-llm.xml

  imixsadmin:
    image: imixs/imixs-admin
    ports:
      - "8888:8080"

  #######################
  # Tika OCR Service
  #######################
  tika:
    image: apache/tika:3.2.0.0-full
    environment:
      TZ: "Europe/Berlin"
    ports:
      - "9998:9998"

volumes:
  dbdata:
