version: "3.1"
services:

  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: office
    volumes: 
      - dbdata:/var/lib/postgresql/data

  app:
    image: imixs/imixs-office-workflow
    depends_on:
      - db
    environment:
      WILDFLY_PASS: adminadmin
     # DEBUG: "true"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/office"
      MAILGATEWAY: "localhost"
      JAVA_OPTS: "$JAVA_OPTS -Dnashorn.args=--no-deprecation-warning"

    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    volumes:
        - ./deployments:/opt/jboss/wildfly/standalone/deployments/

#  imixsadmin:
#    image: imixs/imixs-admin
#    ports:
#      - "8888:8080"

volumes:
  dbdata: 