version: "3.6"
services:
  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: office
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    image: imixs/imixs-office-workflow
    depends_on:
      - db
    environment:
      TZ: "CET"
      LANG: "en_US.UTF-8"
      JAVA_OPTS: "-Dnashorn.args=--no-deprecation-warning"
      MAILGATEWAY: "localhost"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/office"
      # PROFILE_LOGIN_EVENT: "10"
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    volumes:
      - ./deployments:/opt/jboss/wildfly/standalone/deployments/

  # imixsadmin:
  #   image: imixs/imixs-admin
  #   ports:
  #     - "8888:8080"


  # imixsbackup:
  #   image: imixs/imixs-archive-backup:latest
  #   environment:
  #     WILDFLY_PASS: adminadmin
  #     DEBUG: "true"

  #     # EXAMPLE SETUP
  #     WORKFLOW_SERVICE_ENDPOINT: "http://app:8080/api"      
  #     WORKFLOW_SERVICE_USER: admin
  #     WORKFLOW_SERVICE_PASSWORD: "adminadmin"
  #     WORKFLOW_SERVICE_AUTHMETHOD: "form"
      
  #     BACKUP_FTP_HOST: "ftp.storage.foo"
  #     BACKUP_FTP_PATH: "/test/"
  #     BACKUP_FTP_PORT: "21"
  #     BACKUP_FTP_USER: ""
  #     BACKUP_FTP_PASSWORD: ""      
  #   ports:
  #     - "8081:8080"
  

    
 

volumes:
  dbdata:
