version: "3.1"
services:

  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: office
    volumes: 
      - dbdata:/var/lib/postgresql/data
  app:
    image: imixs/imixs-office-workflow
    depends_on:
      - db
    environment:
      JAVA_OPTS: "-Dnashorn.args=--no-deprecation-warning"
      MAILGATEWAY: "localhost"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/office"
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
volumes:
  dbdata: