---
###################################################
# Persistence Volume Claim for DB
###################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata
spec:
  accessModes:
    - ReadWriteOnce
  # The default storageClassName is used here. 
  # You can overwrite the classname
  # storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi


---
###################################################
# Persistence Volume Claim for index
###################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: index
spec:
  accessModes:
    - ReadWriteOnce
  # The default storageClassName is used here. 
  # You can overwrite the classname
  # storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi

