{
 "title": "imixs-office-workflow",
 "time": { "from": "2019-03-11T14:47:07.483Z", "to": "2019-03-11T14:53:39.050Z" },
 "panels": [
  {
   "title": "Documents",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(documents_total[5m]))"
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (workflowgroup) (sum_over_time(workitems_processed_total[1m]))",
     "legendFormat": "{{workflowgroup}}"
    }
   ]
  },
  {
   "title": "Workflow Processing Heat Map",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(workitems_processed_total[5m])"
    }
   ]
  }
 ]
}