{
 "title": "imixs-office-workflow",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Active Workflows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(application_workitems_total{ job='imixs'})"
    }
   ]
  },
  {
   "title": "Active Models",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(application_workitems_total{ job='imixs'})"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "application_transactions_total" }
   ]
  },
  {
   "title": "Workflow Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (workflowgroup) (sum_over_time(application_workitems_total[1m]))",
     "legendFormat": "{{workflowgroup}}"
    }
   ]
  },
  {
   "title": "Data Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(application_documents_total[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}